### ISSUE TITLE
您好，请问test.npy存储的时间序列都是良性流的时间序列吗，我看第51维的数据都是0.00000

### ISSUE THREAD

**Issue by Jiaqi-wow** [XXnormal/RAPIER#3]
您好，请问test.npy存储的时间序列都是良性流的时间序列吗，我看第51维的数据都是0.00000

**Comment by XXnormal** [comment]
感谢您关注我们的工作！我们已对示例数据进行了更新，现在共5000条良性数据和500条恶意数据。
