### ISSUE TITLE
作者你好，请问一下代码data里面的测试用例数据是来自什么数据集的。

### ISSUE THREAD

**Issue by ContentCriminalTaRik** [XXnormal/RAPIER#5]
![image](https://github.com/XXnormal/RAPIER/assets/83114553/c8021225-ac41-4fc1-a5a0-8de7d74cc95f)
1.我执行测试用例提供的数据集，跑了4次，其中两次都出现了只有很低的检测效果，请问可能是什么原因导致的呢？
2.请问具体设置噪声比例的参数在哪里设置？

**Comment by ContentCriminalTaRik** [comment]
似乎Feature_Extract.py，有点问题我想跑CIC-IDS的数据集路径等参数设置都没问题，但是无法产生数据。

**Comment by dingyooo123** [comment]
您好，我也是在复现这个实验，请问您有遇到这个问题吗？
![image](https://github.com/XXnormal/RAPIER/assets/145521862/ddf24949-ad39-4ab9-8c30-a8ac41cdbdaf)

**Comment by XXnormal** [comment]
> ![image](https://private-user-images.githubusercontent.com/83114553/325603177-c8021225-ac41-4fc1-a5a0-8de7d74cc95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTQ4NjEsIm5iZiI6MTcxNDA1NDU2MSwicGF0aCI6Ii84MzExNDU1My8zMjU2MDMxNzctYzgwMjEyMjUtYWM0MS00ZmMxLWE1YTAtOGRlN2Q3NGNjOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE0MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWJmNDIwNjQxYzIwZmQ0NzQ4YTY5NDkwYzNmY2UyOWU4ZTM4YmUwZTZiOTRkYzU4MzFjMjBkNmExMjk1ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvQGpFtmJaDATM8bWL3VQ7x2rmXugCKOVCppMEB015A) 1.我执行测试用例提供的数据集，跑了4次，其中两次都出现了只有很低的检测效果，请问可能是什么原因导致的呢？ 2.请问具体设置噪声比例的参数在哪里设置？

这个图里看的话主要是因为噪声校正的问题，训练样本真正的标签是包含250正常+250异常，这里校正后加上增广后的样本数量有点不正常

**Comment by XXnormal** [comment]
> 似乎Feature_Extract.py，有点问题我想跑CIC-IDS的数据集路径等参数设置都没问题，但是无法产生数据。

是读完文件后get_flows()返回空吗

**Comment by ContentCriminalTaRik** [comment]
> > 似乎Feature_Extract.py，有点问题我想跑CIC-IDS的数据集路径等参数设置都没问题，但是无法产生数据。
> 
> 是读完文件后get_flows()返回空吗

执行之后只创建了两个空文件，可能是我配置有问题具体内部代码我还没看👀

**Comment by ContentCriminalTaRik** [comment]
> 我认为是校正结果不正常，校正后几乎没有异常样本，所以最终recall、precision都非常低吧

主要还是想问下测试用例的数据是什么一些设置，比如标签噪声和具体来自什么数据集，和原文中的哪个实验结果能够对应。

**Comment by XXnormal** [comment]
> > 我认为是校正结果不正常，校正后几乎没有异常样本，所以最终recall、precision都非常低吧
> 
> 主要还是想问下测试用例的数据是什么一些设置，比如标签噪声和具体来自什么数据集，和原文中的哪个实验结果能够对应。明天就pre了来不及跑别的数据集了。😂😂

这个是对应的DoHBrw数据集，是从里面随机挑选的

**Comment by ContentCriminalTaRik** [comment]
感谢！非常有意思的工作！

**Comment by XXnormal** [comment]
> 感谢！非常有意思的工作！ 想问一下前辈，您这块的core observation是先有idea还是先做实验观察的。研一想了解一下科研思路。 ![image](https://private-user-images.githubusercontent.com/83114553/325677285-ea707ba2-7bfb-466c-aac5-a62f9289a00c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjYsIm5iZiI6MTcxNDA1OTcyNiwicGF0aCI6Ii84MzExNDU1My8zMjU2NzcyODUtZWE3MDdiYTItN2JmYi00NjZjLWFhYzUtYTYyZjkyODlhMDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE1NDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NjBhN2M2MzQ0ZjA1Nzg5NTM5YmMxOTFkN2YyODM0YjE2MWI1ZmU3NjE5Zjc0YjU3OGUwMDE3OTU1ZWJmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcHvatA_wbOFkUtVW6v2TTnViSBMayJDDyLnGhztvsE)

先有的idea，之后通过简单实验验证了猜想（标签校正成功），这三张图是更严谨的实验验证

**Comment by dingyooo123** [comment]
同学您好，我也是研一的，冒昧问下，能加好友交流一下吗？ vx:18256288788
